[package]
name = "cddis-archiver"
version = "0.1.0"
edition = "2021"

[dependencies]
hifitime = "4.0.2"
restate-sdk = "0.3.2"
rusty-s3 = "0.7.0"
serde = "1.0.219"
serde_json = "1.0.140"
tokio = { version = "1.44.1", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
